# Configuration file for __main__.py


# File I/O settings
io_settings:
  input_image_name: "input.png"  # USE THIS FOR LIVE SIMULATION, THE REST IS FOR TESTING
#  input_image_name: "input_red_hierarchy.png"
#  input_image_name: "input_red.png"
#  input_image_name: "input_naca_002.png"
#  input_image_name: "input_naca_015.png"
#  input_image_name: "input_naca_030.png"

  output_animation_name: "output.gif"
  particle_plot_name: "particleplot.gif"
  heatmap_pressure_name: "heatmap_pressure.gif"
  heatmap_vorticity_name: "heatmap_vorticity.gif"
  # data_file_name: "simulation_data.npz"

  flip_90_degrees: false # Set o true to show the flow coming from the top rather than the side.

  camera_index: 0

capture_image_aspect_ratio: [3, 2]

simulation_settings:

  # Image recognition settings
  threshold: 0.5  # First play with this until solid shows up, then adjust diff_threshold
  diff_threshold: 0.2  # Increase if too much noise, decrease if solid not showing (only if not using gray)
  solid_color: "gray"  # Options are gray, red, green or blue
  manual_mode: false  # Set to true to use provided threshold values, otherwise smart detection is used
  force_invert_mask: false  # Set to true to force mask inversion if smart logic fails
  image_recognition_debug_mode: true  # Set to true to plot the image recognition mask
  show_components_pca: true  # Set to true to plot the PCA components (image_recognition_debug_mode also needs to be true).

  # Image resolution cap (spatial resolution)
  max_image_res: 800  

  # Simulation duration and temporal resolution
  t_sim: 20.0  # Simulation duration
  delta_t: 0.05  # Temporal resolution

  # Flow settings
  Re: 200.0  # Reynolds number
  epsilon: 1.0  # BDIM kernel width

  # Other settings
  verbose: false

  mem: "Array"  # Memory type: "Array" or "CuArray"
  target_size: [ 800, 800 ]  # Target size for the output GIF

  use_precomputed_results: true  # If true, uses precomputed results instead of running the simulation
  gif_display: "both" # Options: "both", "particle_plot", "heatmap"