# Configuration file for batch simulation runs

aoa_range: [-180, 180, 3]  # Angle of attack range in degrees, [start, end, step]

force_run: false  # If set to true, simulation will run for all cases even if the output file already exists (will
# overwrite existing files)ยง

simulation_settings:
    # Image recognition settings
  image_recognition:
    threshold: 0.5  # First play with this until solid shows up, then adjust diff_threshold
    diff_threshold: 0.2  # Increase if too much noise, decrease if solid not showing (only if not using gray)
    solid_color: "gray"  # Options are gray, red, green or blue
    manual_mode: false  # Set to true to use provided threshold values, otherwise smart detection is used
    force_invert_mask: false  # Set to true to force mask inversion if smart logic fails
    image_recognition_debug_mode: false  # Set to true to plot the image recognition mask and PCA components
    max_image_res: 800  # Image resolution cap (spatial resolution)

  # Simulation parameters
  simulation:
    t_sim: 20.0  # Simulation duration
    delta_t: 0.05  # Temporal resolution
    Re: 200.0  # Reynolds number
    epsilon: 1.0  # BDIM kernel width
    verbose: false
    mem: "Array"  # Memory type: "Array" or "CuArray"
    target_size: [ 800, 800 ]  # Target size for the output GIF